### ISSUE TITLE
Issue with PSGalleryExplorer and future plans

### ISSUE THREAD

**Issue by techthoughts2** [techthoughts2/PSGalleryExplorer#7]
## Description

Dear PSGalleryExplorer users,

I wanted to let you know about an issue that PSGalleryExplorer is currently facing. PSGalleryExplorer extends PowerShell Gallery Module search functionality by including information about a module's associated repository.

The number of modules on the PowerShell Gallery has grown to a level that is no longer scalable with the [current serverless workflow](https://github.com/techthoughts2/PSGalleryExplorer/blob/main/docs/PowerShell_Serverless.md) that PSGalleryExplorer has in place. This necessitates a re-architecture of the way that the repository information is collected and served through AWS cloudfront.

As a result of this change, the current AWS CDN endpoint that PSGalleryExplorer is using will be lost. This means that PSGalleryExplorer will cease to function properly. Current users, that have already downloaded the latest updated repository information, will have that information on their local device. It will grow stale until such time that PSGalleryExplorer is repaired. New users will be unable to use the current version of the module at all.

When PSGalleryExplorer is fixed, any older version of the module will not have context of the new CDN endpoint, and thus, will be unable to download the updated repository information.

I am actively working on repairing PSGalleryExplorer at this time, but it will take some time to complete the re-architecture. I wanted to be transparent with you about this issue and let you know what is going on. I apologize for any inconvenience this may cause.

Thank you for your patience and understanding. If you have any questions or concerns, please feel free to reach out.

Best regards,

@techthoughts2

**Comment by jdhitsolutions** [comment]
You might consider leaving this open as a pinned issue. Or mark the repository as archived. I spent some time trying to figure out why nothing was working until I found this issue.
